"""Zero-cost semantic enrichment.

No LLM, no paid API: every label here is mined from the code itself —
module docstrings, leading comments, exported symbols, framework imports,
and the shape of the import graph. Deterministic and honest. The output
contract is plain data, so a smarter (LLM-backed) enricher can be swapped
in behind the same interface later.
"""

import ast
import posixpath
import re
from collections import Counter, defaultdict

# ---------------------------------------------------------------------------
# Documentation extraction
# ---------------------------------------------------------------------------

_JS_BLOCK_DOC = re.compile(r"^\s*/\*\*?(.*?)\*/", re.S)
_LINE_DOC = re.compile(r"^(?:\s*//+[^\n]*\n)+")
_PY_NOISE = re.compile(r"\s+")
_BOILERPLATE = re.compile(r"copyright|license|licence|spdx|@author|eslint|prettier|auto-generated|generated by", re.I)


def _first_sentence(text: str, limit: int = 160) -> str:
    text = _PY_NOISE.sub(" ", text).strip()
    if not text or _BOILERPLATE.search(text[:200]):
        return ""
    for stop in (". ", ".\n"):
        cut = text.find(stop)
        if 10 <= cut < limit:
            return text[: cut + 1]
    return text[:limit].rstrip() + ("…" if len(text) > limit else "")


def extract_doc(text: str, language: str) -> str:
    """First documentation sentence of a file, if the author wrote one."""
    if language == "python":
        try:
            doc = ast.get_docstring(ast.parse(text))
        except (SyntaxError, ValueError):
            doc = None
        return _first_sentence(doc) if doc else ""

    head = text[:2500]
    m = _JS_BLOCK_DOC.match(head)
    if m:
        body = re.sub(r"^\s*\*\s?", "", m.group(1), flags=re.M)
        return _first_sentence(body)
    m = _LINE_DOC.match(head)
    if m:
        body = re.sub(r"^\s*//+\s?", "", m.group(0), flags=re.M)
        return _first_sentence(body)
    return ""


# ---------------------------------------------------------------------------
# Exported / defined symbols
# ---------------------------------------------------------------------------

_JS_EXPORT = re.compile(
    r"\bexport\s+(?:default\s+)?(?:async\s+)?(?:abstract\s+)?"
    r"(?:function|class|const|let|var|interface|type|enum)\s+([A-Za-z_$][\w$]*)"
)
_GO_DEF = re.compile(r"^(?:func|type)\s+(?:\([^)]*\)\s*)?([A-Z]\w*)", re.M)
_JAVA_DEF = re.compile(r"\b(?:class|interface|enum|record)\s+([A-Z]\w*)")


def extract_symbols(text: str, language: str, max_symbols: int = 5) -> list[str]:
    names: list[str] = []
    if language == "python":
        try:
            tree = ast.parse(text)
        except (SyntaxError, ValueError):
            return []
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                if not node.name.startswith("_"):
                    names.append(node.name)
    elif language in ("javascript", "typescript", "vue", "svelte"):
        names = _JS_EXPORT.findall(text)
    elif language == "go":
        names = _GO_DEF.findall(text)
    elif language == "java":
        names = _JAVA_DEF.findall(text)
    seen: list[str] = []
    for n in names:
        if n not in seen:
            seen.append(n)
    return seen[:max_symbols]


# ---------------------------------------------------------------------------
# File roles — archetypes read off the import graph
# ---------------------------------------------------------------------------

_TEST_PATH = re.compile(r"(^|/)(tests?|__tests__|e2e|spec)(/|$)")
_TEST_NAME = re.compile(r"(^test_|_test\.\w+$|\.(test|spec)\.\w+$)")
_CONFIG_NAME = re.compile(r"^(config|settings|constants|conf)\.\w+$|\.config\.\w+$")
_ENTRY_NAMES = {
    "main.py", "app.py", "server.py", "manage.py", "wsgi.py", "asgi.py", "cli.py",
    "main.ts", "main.tsx", "main.js", "index.ts", "index.js", "app.ts", "app.tsx",
    "main.go", "Main.java", "Application.java",
}


def _percentile(values: list[int], fraction: float) -> int:
    if not values:
        return 0
    ordered = sorted(values)
    return ordered[min(len(ordered) - 1, int(len(ordered) * fraction))]


def classify_roles(
    files: list[str],
    edges: set[tuple[str, str]],
) -> dict[str, str]:
    in_deg = Counter(t for _, t in edges)
    out_deg = Counter(s for s, _ in edges)
    cross = Counter()
    for s, t in edges:
        if s.split("/")[0] != t.split("/")[0]:
            cross[s] += 1
            cross[t] += 1

    hub_floor = max(3, _percentile([v for v in in_deg.values() if v], 0.9))
    orch_floor = max(5, _percentile([v for v in out_deg.values() if v], 0.9))

    roles: dict[str, str] = {}
    for rel in files:
        name = posixpath.basename(rel)
        if _TEST_PATH.search(rel) or _TEST_NAME.search(name):
            roles[rel] = "test"
        elif _CONFIG_NAME.match(name):
            roles[rel] = "config"
        elif name in _ENTRY_NAMES and out_deg[rel] >= 2 and in_deg[rel] <= 1:
            roles[rel] = "entry point"
        elif in_deg[rel] >= hub_floor:
            roles[rel] = "core hub"
        elif cross[rel] >= 3:
            roles[rel] = "bridge"
        elif out_deg[rel] >= orch_floor:
            roles[rel] = "orchestrator"
        elif in_deg[rel] == 0 and out_deg[rel] == 0:
            roles[rel] = "isolated"
        else:
            roles[rel] = "module"
    return roles


# ---------------------------------------------------------------------------
# Cluster (directory) labelling
# ---------------------------------------------------------------------------

_DIR_KINDS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"(^|/)(routes?|routers?|endpoints?|controllers?)$"), "API endpoints"),
    (re.compile(r"(^|/)(models?|schemas?|entities)$"), "data models"),
    (re.compile(r"(^|/)types?$"), "type definitions"),
    (re.compile(r"(^|/)(components?|ui|widgets?)$"), "UI components"),
    (re.compile(r"(^|/)hooks$"), "UI hooks"),
    (re.compile(r"(^|/)(utils?|helpers?|common|shared|lib)$"), "shared utilities"),
    (re.compile(r"(^|/)(tests?|__tests__|e2e|spec)$"), "tests"),
    (re.compile(r"(^|/)core$"), "core infrastructure"),
    (re.compile(r"(^|/)services?$"), "service layer"),
    (re.compile(r"(^|/)middlewares?$"), "middleware"),
    (re.compile(r"(^|/)(auth|authentication)$"), "authentication"),
    (re.compile(r"(^|/)(db|database|crud|repositor(y|ies)|dao|store)$"), "data access"),
    (re.compile(r"(^|/)(cli|commands?|scripts?)$"), "command-line tools"),
    (re.compile(r"(^|/)(views?|pages?|screens?)$"), "pages & views"),
    (re.compile(r"(^|/)client$"), "API client"),
    (re.compile(r"(^|/)(workers?|jobs?|tasks?|queues?)$"), "background jobs"),
    (re.compile(r"(^|/)(api)$"), "API layer"),
    (re.compile(r"(^|/)examples?$"), "examples"),
]

_REACTISH = re.compile(r"from\s+['\"]react['\"]|require\(['\"]react['\"]\)")
_API_FRAMEWORK = re.compile(
    r"\b(APIRouter|FastAPI|Blueprint|express\.Router|@(Get|Post|Put|Delete)Mapping|@app\.(get|post|put|delete))\b"
)
_ORM = re.compile(r"\b(SQLModel|declarative_base|sqlalchemy|prisma|TypeORM|gorm)\b", re.I)


_JSX_EXTS = (".tsx", ".jsx", ".vue", ".svelte")
_BACKEND_LANGS = {"python", "go", "java"}


def _dir_kind(
    dir_path: str,
    members: list[str],
    sources: dict[str, str],
    languages: dict[str, str],
    roles: dict[str, str],
) -> str:
    # Majority-test dirs are tests no matter what they're called.
    if members and sum(1 for m in members if roles.get(m) == "test") / len(members) > 0.5:
        return "tests"
    jsx_fraction = sum(1 for m in members if m.endswith(_JSX_EXTS)) / max(1, len(members))
    for pattern, kind in _DIR_KINDS:
        if pattern.search(dir_path):
            # routes/ full of JSX is a page router, not an HTTP API
            if kind in ("API endpoints", "API layer") and jsx_fraction >= 0.5:
                return "pages & views"
            return kind
    if jsx_fraction >= 0.5:
        return "UI components"
    sample = [sources[m][:4000] for m in members[:12]]
    if sum(1 for s in sample if _REACTISH.search(s)) >= max(2, len(sample) // 2):
        return "UI components"
    # Framework/ORM tokens prove nothing inside UI strings — only trust them
    # in backend languages.
    backend_sample = [
        sources[m][:4000] for m in members[:12] if languages[m] in _BACKEND_LANGS
    ]
    if any(_API_FRAMEWORK.search(s) for s in backend_sample):
        return "API endpoints"
    if any(_ORM.search(s) for s in backend_sample):
        return "data layer"
    return ""


def _pretty_label(dir_path: str, taken: set[str]) -> str:
    parts = dir_path.split("/")
    for k in range(1, len(parts) + 1):
        label = "/".join(parts[-k:])
        if label not in taken:
            taken.add(label)
            return label
    return dir_path


def build_clusters(
    files: list[str],
    sources: dict[str, str],
    languages: dict[str, str],
    significance: dict[str, float],
    roles: dict[str, str],
    min_size: int = 3,
    max_clusters: int = 16,
) -> list[dict]:
    by_dir: dict[str, list[str]] = defaultdict(list)
    for rel in files:
        by_dir[posixpath.dirname(rel)].append(rel)

    candidates = sorted(
        ((d, members) for d, members in by_dir.items() if len(members) >= min_size),
        key=lambda kv: -len(kv[1]),
    )[:max_clusters]

    clusters = []
    taken: set[str] = set()
    for dir_path, members in candidates:
        lang_counts = Counter(languages[m] for m in members)
        dominant_lang = lang_counts.most_common(1)[0][0]
        anchor = max(members, key=lambda m: significance.get(m, 0.0))
        kind = _dir_kind(dir_path, members, sources, languages, roles)
        bits = [f"{len(members)} {dominant_lang} files"]
        if kind:
            bits.append(kind)
        bits.append(f"anchored by {posixpath.basename(anchor)}")
        clusters.append(
            {
                "dir": dir_path,
                "label": _pretty_label(dir_path or "root", taken),
                "kind": kind,
                "description": " · ".join(bits),
                "count": len(members),
                "language": dominant_lang,
                "anchor": anchor,
            }
        )
    return clusters


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def describe_file(doc: str, symbols: list[str]) -> str:
    if doc:
        return doc
    if symbols:
        return "Defines " + ", ".join(symbols)
    return ""


def enrich(
    sources: dict[str, str],
    languages: dict[str, str],
    edges: set[tuple[str, str]],
    significance: dict[str, float],
) -> tuple[dict[str, dict], list[dict]]:
    """Returns ({file: {role, description}}, clusters)."""
    files = sorted(sources)
    roles = classify_roles(files, edges)
    extras: dict[str, dict] = {}
    for rel in files:
        doc = extract_doc(sources[rel], languages[rel])
        symbols = extract_symbols(sources[rel], languages[rel])
        extras[rel] = {
            "role": roles[rel],
            "description": describe_file(doc, symbols),
        }
    clusters = build_clusters(files, sources, languages, significance, roles)
    return extras, clusters
